name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # (Optional) Faster installs on repeated runs
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Migrate DB
        env:
          DATABASE_URL: "sqlite:///./test.db"
        run: |
          alembic upgrade head

      - name: Run tests (start server for E2E)
        env:
          DATABASE_URL: "sqlite:///./test.db"
        shell: bash
        run: |
          # start uvicorn in background
          uvicorn app.main:app --host 127.0.0.1 --port 8000 &
          UVICORN_PID=$!
          # give it a moment to boot
          sleep 3
          # run tests
          pytest -q
          # always stop server
          kill $UVICORN_PID || true

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/is601final:latest
